<?php

declare(strict_types=1);

/**
 * PHP CS Fixer configuration for this project. For documentation @see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/config.rst
 */

$finder = PhpCsFixer\Finder::create()                       // @phpstan-ignore class.notFound (class lives in phar file and can't be seen)
    ->in(__DIR__)
    ->exclude([
        ...require(__DIR__ . '/vendor/youwe/testing-suite/config/pimcore/php-cs-fixer/excludes.php'),

        /**
         * List your application specific exclude paths here
         */

        // example: 'autogenerated_content',
    ]);

$config = new PhpCsFixer\Config();                          // @phpstan-ignore class.notFound (class lives in phar file and can't be seen)
return $config                                              // @phpstan-ignore class.notFound (class lives in phar file and can't be seen)
    ->setRules(array_merge_recursive(
        require(__DIR__ . '/vendor/youwe/testing-suite/config/pimcore/php-cs-fixer/rules.php'),
        [
            /**
             * Add your application specific overrides here
             * @see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/ruleSets/index.rst for available rule sets
             * @see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/index.rst for individual rules
             */

             // example: '@PER-CS:risky' => true,
             // example: 'array_syntax' => ['syntax' => 'short'],
        ]
    ))
    ->setFinder($finder);
