imports:
  - resource: '../default/grumphp.yml'

# Extend git triggers with common pimcore constructs
parameters:
  git_blacklist.triggered_by: [ 'php', 'js', 'twig' ]

  # Disable PHPCS (which is enabled by default) in favour of PHP CS Fixer
  phpcs.enabled: false
  phpcsfixer.enabled: true

#  securitychecker.allow_list:
#    - CVE-2002-0121 # Add a jira ticket indicating when this vulnerability will be fixed (update/upgrade will be
                     #    performed). Within that ticket explain this (new) vulnerability.
